# Generated by Django 4.2.7 on 2023-12-06 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_studentresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='assessment.assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.question'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='selected_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.choice'),
        ),
    ]
