# Generated by Django 4.2.7 on 2023-12-08 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_studentresponse_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
