# Generated by Django 4.2.7 on 2023-12-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_studentassessmentscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('threshold', models.IntegerField()),
            ],
        ),
    ]
