# Generated by Django 4.2.7 on 2023-12-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_alter_gradesystem_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradesystem',
            old_name='threshold',
            new_name='max_score',
        ),
        migrations.AddField(
            model_name='gradesystem',
            name='min_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
