# Generated by Django 4.2.7 on 2024-01-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_rename_threshold_gradesystem_max_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessmentscore',
            name='score',
            field=models.CharField(max_length=255),
        ),
    ]
