# Generated by Django 4.2.7 on 2024-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_studentassessmentscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='structure',
            field=models.CharField(choices=[('text', 'Text'), ('mixed', 'Mixed'), ('mcq', 'Multiple Choice')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('ca', 'CA')], default='ca', max_length=20),
        ),
    ]
