# Generated by Django 4.2.7 on 2024-02-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_assessment_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
