# Generated by Django 4.2.7 on 2024-02-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_assessment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark_allocated',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
