# Generated by Django 4.2.7 on 2024-02-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_question_mark_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='text_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
