# Generated by Django 4.2.7 on 2024-02-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_studentresponse_text_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assessment.choice'),
        ),
    ]
