# Generated by Django 4.2.7 on 2024-02-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_alter_studentresponse_selected_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessmentscore',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
