# Generated by Django 4.2.7 on 2024-02-21 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_studentassessmentscore_is_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessmentscore',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assessment.question'),
        ),
    ]
