# Generated by Django 4.2.7 on 2024-02-26 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_librarybook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0018_studentassessmentscore_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('meeting_id', models.CharField(max_length=255, unique=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('join_url', models.URLField()),
                ('password', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
