# Generated by Django 4.2.7 on 2024-02-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_zoommeeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoomMeeting',
        ),
    ]
