# Generated by Django 4.2.6 on 2023-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbrev', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
    ]
