# Generated by Django 4.2.7 on 2023-12-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_faculty_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.department'),
        ),
    ]
