# Generated by Django 4.2.7 on 2024-01-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_level_faculty_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='levels',
            field=models.ManyToManyField(blank=True, to='faculty.level'),
        ),
    ]
