# Generated by Django 4.2.7 on 2024-01-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_faculty_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abbrev',
            field=models.CharField(default='CE', max_length=10),
            preserve_default=False,
        ),
    ]
