# Generated by Django 4.2.7 on 2024-02-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_job_city_job_company_job_experience_job_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
