# Generated by Django 4.2.7 on 2024-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_chatgroup_code_chatgroup_members'),
        ('students', '0015_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered_groups',
            field=models.ManyToManyField(blank=True, related_name='student_members', to='courses.chatgroup'),
        ),
    ]
