# Generated by Django 4.2.7 on 2024-01-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_registered_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registered_groups',
        ),
    ]
