# Generated by Django 4.2.7 on 2023-12-12 12:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('id_card_number', models.CharField(max_length=20, unique=True)),
                ('scanned_id_document', models.FileField(upload_to='scanned_id_documents/')),
                ('primary_location', models.CharField(max_length=255)),
                ('secondary_location', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian1_name', models.CharField(max_length=255)),
                ('guardian1_contact', models.CharField(max_length=15)),
                ('guardian2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian2_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('motivation_letter', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='AchievementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='achievement_documents/')),
                ('description', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_achievements', to='applicants.applicant')),
            ],
        ),
    ]
