# Generated by Django 4.2.7 on 2023-12-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
