# Generated by Django 4.2.7 on 2023-12-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_achievementdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementdocument',
            name='document',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='scanned_id_document',
            field=models.CharField(max_length=255),
        ),
    ]
