# Generated by Django 4.2.7 on 2023-12-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_department'),
        ('applicants', '0006_applicant_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.faculty'),
        ),
    ]
