# Generated by Django 4.2.7 on 2023-12-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_department'),
        ('applicants', '0007_applicant_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.department'),
        ),
    ]
