# Generated by Django 4.2.7 on 2023-12-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_applicant_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='Department',
            new_name='department',
        ),
    ]
