# Generated by Django 4.2.7 on 2023-12-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_rename_department_applicant_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=8),
            preserve_default=False,
        ),
    ]
