# Generated by Django 4.2.7 on 2023-11-17 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_rename_instructor_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('open', 'Open for Enrollment'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='Open', max_length=20),
        ),
    ]
