# Generated by Django 4.2.7 on 2023-11-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_modified_by_alter_course_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_materials',
        ),
    ]
