# Generated by Django 4.2.7 on 2024-01-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assessment_and_grading',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_objectives',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
