# Generated by Django 4.2.7 on 2024-01-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_chatgroup_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.message'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
