# Generated by Django 4.2.7 on 2024-01-19 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_message_attachment_message_response_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='code',
            field=models.CharField(default='12347890', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chat_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
