# Generated by Django 4.2.7 on 2024-01-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_chatgroup_code_chatgroup_members'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='group_messages',
        ),
    ]
