# Generated by Django 4.2.7 on 2024-01-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_message_groupmessage_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='response_to',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
