# Generated by Django 4.2.7 on 2024-01-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
