# Generated by Django 4.2.7 on 2024-01-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_course_level'),
        ('teachers', '0003_teacher_about_teacher_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='instructed_courses', to='courses.course'),
        ),
    ]
