# Generated by Django 4.2.7 on 2024-01-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_course_level'),
        ('teachers', '0004_teacher_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='tutors', to='courses.course'),
        ),
    ]
