# Generated by Django 4.2.7 on 2024-02-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal')], default='stripe', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='status',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal')], default='pending', max_length=20),
        ),
    ]
