# Generated by Django 4.2.7 on 2024-02-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_userpayment_payment_method_alter_userpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='paypal_checkout_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
