# Generated by Django 4.2.6 on 2023-10-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
    ]
