# Generated by Django 4.2.6 on 2023-10-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_enrollment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='activate_date',
        ),
    ]
