# Generated by Django 4.2.6 on 2023-10-26 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
