# Generated by Django 4.2.6 on 2023-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reference',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
