# Generated by Django 4.2.6 on 2023-11-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_student_reference_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
