# Generated by Django 4.2.7 on 2023-11-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_created_by'),
        ('students', '0012_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.faculty'),
        ),
    ]
