# Generated by Django 4.2.7 on 2023-11-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_modified_by_alter_course_course_status'),
        ('students', '0013_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
    ]
