# Generated by Django 4.2.7 on 2024-01-25 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
