# Generated by Django 4.2.7 on 2024-01-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_chatgroup_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='response_to',
        ),
    ]
