# Generated by Django 4.2.6 on 2023-10-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_studen',
            field=models.BooleanField(default=False),
        ),
    ]
