# Generated by Django 4.2.6 on 2023-10-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_studen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_studen',
        ),
    ]
