# Generated by Django 4.2.6 on 2023-10-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_studen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_studentt',
            field=models.BooleanField(default=False),
        ),
    ]
