# Generated by Django 4.2.6 on 2023-10-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_studentt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locked_at',
        ),
    ]
