# Generated by Django 4.2.6 on 2023-10-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_failed_attempts_remove_user_locked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_requested_at',
        ),
    ]
