# Generated by Django 4.2.6 on 2023-10-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_is_teacher_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_studentt',
            new_name='is_a_student',
        ),
        migrations.AddField(
            model_name='user',
            name='is_a_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
