# Generated by Django 4.2.6 on 2023-10-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_is_studentt_user_is_a_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='delete_request_timestamp',
        ),
    ]
