# Generated by Django 4.2.6 on 2023-11-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
