# Generated by Django 4.2.7 on 2023-11-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_password_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'other')], default='male', max_length=10),
            preserve_default=False,
        ),
    ]
