# Generated by Django 4.2.7 on 2024-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_phone_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Cameroonian', max_length=255),
            preserve_default=False,
        ),
    ]
